name: Rails CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build and Test
              run: |
                  echo "uncomment after generating the app"
                  # docker compose build
                  # docker compose run --rm web bundle install
                  # docker compose run --rm web bundle exec rails db:create
                  # docker compose run --rm web bundle exec rails db:migrate
                  # docker compose run --rm web bundle exec rspec
