name: Rails CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build and Test
              run: |
                  docker compose build
                  docker compose run --rm web bundle install
                  docker compose run --rm web bundle exec rails db:create
                  docker compose run --rm web bundle exec rails db:migrate
                  docker compose run --rm web bundle exec rspec
